Imp: add plugins log configuration
        Add fix for services configuration and other small fixes

diff --git a/bootstrap-src-functions b/bootstrap-src-functions
--- a/bootstrap-src-functions
+++ b/bootstrap-src-functions
@@ -20,7 +20,9 @@ OPENBATON_TMP_FOLDER=`mktemp -d`
 OPENBATON_INSTALLATION_BASE_DIR=/opt
 OPENBATON_BASE_DIR="${OPENBATON_INSTALLATION_BASE_DIR}/openbaton"
 OPENBATON_BASE_CONFIG_DIR="/etc/openbaton"
-OPENBATON_LOG="/var/log/openbaton"
+OPENBATON_LOG_DIR="/var/log/openbaton"
+OPENBATON_PLUGINS_LOG_DIR="plugins"
+OPENBATON_PLUGINS_LOG_DIR_ABSOLUTE="${OPENBATON_LOG_DIR}/${OPENBATON_PLUGINS_LOG_DIR}"
 OPENBATON_NFVO_DIR="${OPENBATON_BASE_DIR}/nfvo"
 OPENBATON_PLUGINS_DIR="${OPENBATON_NFVO_DIR}/plugins"
 OPENBATON_PLUGINS_VIMDRIVERS_DIR="${OPENBATON_PLUGINS_DIR}/vim-drivers"
@@ -54,54 +56,56 @@ src_configure_rabbitmq_for_nfvo () {
     log_success_msg "Configuring RabbitMQ for the Open Baton NFVO"
 
     result=$(ps aux | grep -v 'grep' | grep 'rabbitmq' | wc -l)
-    if [ ${result} -gt 0 ]; then
-        result=$($_ex 'rabbitmqctl list_users' | grep '^admin' | wc -l)
-        if [ ${result} -eq 0 ]; then
-            # Check the NFVO version being installed: the new RabbitMQ configuration is required only from version >= 4.0.1
-            compare_version_strings "4.0.0" "${openbaton_nfvo_version}"
-            result=$?
-            if [ ${result} -eq 1 ]; then
-                export rabbitmq_admin_password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32)
-
-                # Set the rabbitmq 'admin' password if different from the default one which is 'openbaton'
-                export OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE=${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}
-                log_success_msg "Setting new 'admin' password: ${rabbitmq_admin_password}"
-                log_warning_msg "The 'admin' password has been randomly generated and you can find it in the '${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}' properties file as the value of the 'spring.rabbitmq.password' property"
-                $_ex 'sed -i "s|spring.rabbitmq.password\s*=\s*.*|spring.rabbitmq.password=${rabbitmq_admin_password}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
-            else
-                export rabbitmq_admin_password="openbaton"
-            fi
-
-            $_ex 'rabbitmqctl add_user admin ${rabbitmq_admin_password}'
-            $_ex 'rabbitmqctl set_user_tags admin administrator'
-            $_ex 'rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"'
-            $_ex 'rabbitmq-plugins enable rabbitmq_management'
-            $_ex 'service rabbitmq-server restart'
-            if [ "$?" != "0" ]; then
-                echo " * ERROR: RabbitMQ is NOT running properly (check the problem in /var/log/rabbitmq)"
-                exit 1
-            fi
-        fi
-
-        # In case of "noninteractive" FRONTEND either the value from the configuration file or the default value will be used (DEFAULT: rabbitmq_broker_ip=localhost ; rabbitmq_management_port=15672)
-        if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-            read -p " * Enter the rabbitmq broker ip [localhost]: " rabbitmq_broker_ip
-            read -p " * Enter the rabbitmq management port [15672]: " rabbitmq_management_port
-        fi
-
-        export OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE=${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}
-
-        # Set the rabbitmq broker ip
-        export rabbitmq_broker_ip=${rabbitmq_broker_ip:-$RABBITMQ_BROKER_IP_DEFAULT}
-        export rabbitmq_broker_ip=${rabbitmq_broker_ip:-$RABBITMQ_BROKER_IP_DEFAULT}
-        echo " * Setting new broker IP: ${rabbitmq_broker_ip}"
-        $_ex 'sed -i "s|nfvo.rabbit.brokerIp\s*=\s*localhost|nfvo.rabbit.brokerIp=${rabbitmq_broker_ip}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
-
-        # Set the rabbitmq management port
-        export rabbitmq_management_port=${rabbitmq_management_port:-$RABBITMQ_MANAGEMENT_PORT_DEFAULT}
-        echo " * Setting new management port: ${rabbitmq_management_port}"
-        $_ex 'sed -i "s|nfvo.rabbit.management.port\s*=\s*15672|nfvo.rabbit.management.port=${rabbitmq_management_port}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
+    if [ ${result} -eq 0 ]; then
+        $_ex 'rabbitmq-server start -detached'
     fi
+
+    result=$($_ex 'rabbitmqctl list_users' | grep '^admin' | wc -l)
+    if [ ${result} -eq 0 ]; then
+        # Check the NFVO version being installed: the new RabbitMQ configuration is required only from version >= 4.0.1
+        compare_version_strings "4.0.0" "${openbaton_nfvo_version}"
+        result=$?
+        if [ ${result} -eq 1 ]; then
+            export rabbitmq_admin_password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32)
+
+            # Set the rabbitmq 'admin' password if different from the default one which is 'openbaton'
+            export OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE=${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}
+            log_success_msg "Setting new 'admin' password: ${rabbitmq_admin_password}"
+            log_warning_msg "The 'admin' password has been randomly generated and you can find it in the '${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}' properties file as the value of the 'spring.rabbitmq.password' property"
+            $_ex 'sed -i "s|spring.rabbitmq.password\s*=\s*.*|spring.rabbitmq.password=${rabbitmq_admin_password}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
+        else
+            export rabbitmq_admin_password="openbaton"
+        fi
+
+        $_ex 'rabbitmqctl add_user admin ${rabbitmq_admin_password}'
+        $_ex 'rabbitmqctl set_user_tags admin administrator'
+        $_ex 'rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"'
+        $_ex 'rabbitmq-plugins enable rabbitmq_management'
+        $_ex 'service rabbitmq-server restart'
+        if [ "$?" != "0" ]; then
+            echo " * ERROR: RabbitMQ is NOT running properly (check the problem in /var/log/rabbitmq)"
+            exit 1
+        fi
+    fi
+
+    # In case of "noninteractive" FRONTEND either the value from the configuration file or the default value will be used (DEFAULT: rabbitmq_broker_ip=localhost ; rabbitmq_management_port=15672)
+    if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
+        read -p " * Enter the rabbitmq broker ip [localhost]: " rabbitmq_broker_ip
+        read -p " * Enter the rabbitmq management port [15672]: " rabbitmq_management_port
+    fi
+
+    export OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE=${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}
+
+    # Set the rabbitmq broker ip
+    export rabbitmq_broker_ip=${rabbitmq_broker_ip:-$RABBITMQ_BROKER_IP_DEFAULT}
+    export rabbitmq_broker_ip=${rabbitmq_broker_ip:-$RABBITMQ_BROKER_IP_DEFAULT}
+    echo " * Setting new broker IP: ${rabbitmq_broker_ip}"
+    $_ex 'sed -i "s|nfvo.rabbit.brokerIp\s*=\s*localhost|nfvo.rabbit.brokerIp=${rabbitmq_broker_ip}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
+
+    # Set the rabbitmq management port
+    export rabbitmq_management_port=${rabbitmq_management_port:-$RABBITMQ_MANAGEMENT_PORT_DEFAULT}
+    echo " * Setting new management port: ${rabbitmq_management_port}"
+    $_ex 'sed -i "s|nfvo.rabbit.management.port\s*=\s*15672|nfvo.rabbit.management.port=${rabbitmq_management_port}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
 }
 
 src_configure_rabbitmq_for_vnfm_generic () {
@@ -152,6 +156,17 @@ src_configure_rabbitmq_for_vnfm_generic () {
 ############################
 #### VIM-Driver Plugins ####
 ############################
+
+src_set_plugins_log_folder () {
+    export OPENBATON_PLUGINS_LOG_DIR_ABSOLUTE=${OPENBATON_PLUGINS_LOG_DIR_ABSOLUTE}
+
+    log_success_msg "Creating directory for Plugins logs"
+    $_ex 'mkdir -p ${OPENBATON_PLUGINS_LOG_DIR_ABSOLUTE}'
+    $_ex 'chown -R '"${USER}:${USER} ${OPENBATON_PLUGINS_LOG_DIR_ABSOLUTE}"
+
+    log_success_msg "Configuring directory for Plugins logs"
+    $_ex 'sed -i "s|nfvo.plugin.log.path\s*=\s*.*|nfvo.plugin.log.path=${OPENBATON_PLUGINS_LOG_DIR_ABSOLUTE}|g" ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}'
+}
 
 src_compile_plugin () {
     component_name="${1}"                       # the directory on which the repo has been cloned
@@ -219,15 +234,15 @@ src_create_openbaton_base () {
     # removing it if exists
     $_ex 'rm -rf '"${OPENBATON_BASE_DIR}"
     $_ex 'mkdir -p '"${OPENBATON_NFVO_DIR}"
-    $_ex 'chown -R '"${USER} $OPENBATON_BASE_DIR"
+    $_ex 'chown -R '"${USER}:${USER} $OPENBATON_BASE_DIR"
 }
 
 src_create_openbaton_log () {
     echo " * Creating the Open Baton log folder .."
     # removing it if exists
-    $_ex 'rm -rf '"${OPENBATON_LOG}"
-    $_ex 'mkdir -p '"${OPENBATON_LOG}"
-    $_ex 'chown -R '"${USER} ${OPENBATON_LOG}"
+    $_ex 'rm -rf '"${OPENBATON_LOG_DIR}"
+    $_ex 'mkdir -p '"${OPENBATON_LOG_DIR}"
+    $_ex 'chown -R '"${USER}:${USER} ${OPENBATON_LOG_DIR}"
 }
 
 src_checkout_nfvo () {
@@ -580,6 +595,9 @@ src_bootstrap () {
     src_configure_rabbitmq_for_nfvo "${openbaton_nfvo_version}"
     install_mysql
 
+    # Plugins configuration for NFVO
+    src_set_plugins_log_folder
+
     #
     # Arguments of "src_checkout_additional_component": component_repo_url component_name(the directory on which the repo will be locally cloned) component_name_fancy component_properties_file_src component_properties_file_dest install_during_noninteractive_installation oldest_component_version_supported component_version
     #
@@ -608,9 +626,6 @@ src_bootstrap () {
         git checkout develop
         pip install .
     fi
-
-    # Plugins configuration for NFVO
-    configure_plugins_logs_dir
 
     wait_for_nfvo_up
 
