Imp: initial commit for whiptail support

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -31,6 +31,8 @@ OPENBATON_BOOTSTRAP_ENV_FILE="/tmp/bootstrap_env"
 OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL=http://get.openbaton.org/bootstraps/
 
 USER="$(id -un 2>/dev/null || true)"
+DEBIAN_FRONTEND_DEFAULT="dialog"
+export DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-$DEBIAN_FRONTEND_DEFAULT}
 
 OS_ARCHITECTURE=$(uname -m)
 OS_TYPE=$(uname -a | awk -F' ' '{ print $1 }')
@@ -65,7 +67,8 @@ OPENBATON_BOOTSTRAP_SUBCOMMAND_DEFAULT=release
 ###############
 
 usage () {
-    echo " * Usage: (The 'release' installation is the DEFAULT)"
+    echo ""
+    echo " * USAGE: (The 'release' installation is the DEFAULT)"
     echo "    ./bootstrap [help | clean | enable-persistence | configure-remote-rabbitmq] | [[release | develop] [--openbaton-bootstrap-version=X.Y.Z (with X.Y.Z >= 3.2.0)] [--config-file=<absolute path to configuration file>]]                                         (if bootstrap already locally available)"
     echo "    sh <(curl -s http://get.openbaton.org/bootstrap) [help | clean | enable-persistence | configure-remote-rabbitmq] | [[release | develop] [--openbaton-bootstrap-version=X.Y.Z (with X.Y.Z >= 3.2.0)] [--config-file=<absolute path to configuration file>]]    (otherwise)"
     echo ""
@@ -103,16 +106,16 @@ fi
 ##############
 
 prereq () {
-    $_ex 'apt-get install -y wget'
+    $_ex 'apt-get install -y wget whiptail'
 
-    wget -O bootstrap-common-functions "${OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL}/${openbaton_bootstrap_version}/bootstrap-common-functions"
+    #wget -O bootstrap-common-functions "${OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL}/${openbaton_bootstrap_version}/bootstrap-common-functions"
     . ./bootstrap-common-functions
 }
 
 main_src () {
     prereq
 
-    wget -O bootstrap-src-functions "${OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL}/${openbaton_bootstrap_version}/bootstrap-src-functions"
+    #wget -O bootstrap-src-functions "${OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL}/${openbaton_bootstrap_version}/bootstrap-src-functions"
     . ./bootstrap-src-functions
     src_bootstrap
 }
@@ -120,7 +123,7 @@ main_src () {
 main_deb () {
     prereq
 
-    wget -O bootstrap-deb-functions "${OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL}/${openbaton_bootstrap_version}/bootstrap-deb-functions"
+    #wget -O bootstrap-deb-functions "${OPENBATON_BOOTSTRAP_FUNCTIONS_BASE_URL}/${openbaton_bootstrap_version}/bootstrap-deb-functions"
     . ./bootstrap-deb-functions
     deb_bootstrap "${1}" "${2}"           # ${1} = release/nightly ; ${2} = distribution codename
 }
@@ -128,29 +131,108 @@ main_deb () {
 main () {
     # In case of "noninteractive" FRONTEND the latest RELEASE package will be installed
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-        echo " * Welcome to the Open Baton menu installation."
-        echo " * Available installation types are the following:"
-        echo "    1. develop (SOURCE): it will be downloaded the source code for all the components which will be executed in screens"
-        echo "    2. release (DEBIAN): it will be installed the binary version of the latest released version"
-        echo "    3. nightly (DEBIAN): it will be installed the binary version of the latest nightly build"
-        read -p " * Select the Open Baton installation type you prefer [2]: " install_type
-        case ${install_type} in
+        bootstrap_subcommand=$( whiptail --title "Open Baton General Menu" --menu "\nPlease, choose the operation to be executed:" 15 140 5 \
+            "1" "Print Open Baton usage" \
+            "2" "Procede with the Open Baton installation" \
+            "3" "Procede with the Open Baton installation cleaning" \
+            "4" "Enable the Open Baton persistence" \
+            "5" "Configure a remote RabbitMQ instance to work with Open Baton" 3>&1 1>&2 2>&3 )
+
+        case ${bootstrap_subcommand} in
             1 ) 
-                main_src 
+                bootstrap_subcommand="help"
+                ;;
+            2 )
+                bootstrap_subcommand="install"
                 ;;
             3 ) 
-                main_deb nightly "${OS_DISTRIBUTION_CODENAME}"
+                bootstrap_subcommand="clean"
                 ;;
-            * ) 
-                main_deb release "${OS_DISTRIBUTION_CODENAME}"
+            4 )
+                bootstrap_subcommand="enable-persistence"
+                ;;
+            5 )
+                bootstrap_subcommand="configure-remote-rabbitmq"
                 ;;
         esac
+
+        if [ -z "${bootstrap_subcommand}" ]; then
+            log_warning_msg "Exiting Open Baton Menu."
+            exit 0
+        elif [ "${bootstrap_subcommand}" = "install" ]; then
+            install_type=$( whiptail --title "Open Baton Installation Menu" --menu "\nPlease, choose the preferred Open Baton installation:" 15 140 5 \
+                "1" "RELEASE: it will be executed the installation of the DEBIAN packages of the latest released components" \
+                "2" "DEVELOP: it will be executed the download of the SOURCE code for the desired components (which will be run in screens)" 3>&1 1>&2 2>&3 )
+            case ${install_type} in
+                1 )
+                    main_deb release "${OS_DISTRIBUTION_CODENAME}"
+                    ;;
+                2 )
+                    main_src
+                    ;;
+                #3 )
+                #    main_deb nightly "${OS_DISTRIBUTION_CODENAME}"
+                #    ;;
+                * )
+                    log_warning_msg "Open Baton installation aborted."
+                    exit 1
+                    ;;
+            esac
+        else
+            exec_bootstrap_subcommand "${bootstrap_subcommand}"
+        fi
     else
         # Non interactive debian release installation with the default values (when non interactive installation and no config file has been passed)
         main_deb release "${OS_DISTRIBUTION_CODENAME}"
     fi
 
-    log_success_msg "Open Baton installation complete"
+    log_success_msg "Open Baton operation completed"
+}
+
+exec_bootstrap_subcommand () {
+    bootstrap_subcommand="${1}"
+
+    case ${bootstrap_subcommand} in
+        "help")
+            usage
+            exit 1
+            ;;
+        "release" )
+            echo " * Installing the latest RELEASE package"
+            main_deb release "${OS_DISTRIBUTION_CODENAME}"
+            ;;
+        "develop" )
+            # Check for OS: the develop installation works (i.e.: it has been tested) on Ubuntu 16.04 or later
+            if [ "${OS_DISTRIBUTION_ID}" = "Ubuntu" -a "${OS_DISTRIBUTION_RELEASE}" \< "16.04" ]; then
+                echo " * Sorry, If you want to install the source code through this bootstrap you need a machine with Ubuntu Xenial (16.04) or later."
+                echo " * In case you want to install the source code on a different OS you need to manually install Java 8 (if needed) and clone the repositories from ${OPENBATON_HOME_REPO_URL}"
+                exit 0
+            fi
+
+            echo " * Installing the latest source code"
+            main_src
+            ;;
+        "clean" )
+            echo " * Cleaning the Open Baton installation"
+            prereq
+            clean
+            exit 0
+            ;;
+        "enable-persistence" )
+            prereq
+            install_mysql
+            exit 0
+            ;;
+        "configure-remote-rabbitmq" )
+            prereq
+            configure_remote_rabbitmq
+            exit 0
+            ;;
+        "*")
+            usage
+            exit 1
+            ;;
+    esac
 }
 
 
@@ -163,6 +245,7 @@ if [ -n "${1+1}" ]; then
         rm ${OPENBATON_BOOTSTRAP_ENV_FILE}
     fi
 
+    bootstrap_subcommand=""
     for arg in $@ ; do
         arg_id=$(echo $arg | cut -c1-2)
         arg_key=${arg}
@@ -227,62 +310,38 @@ if [ -n "${1+1}" ]; then
         . ${OPENBATON_BOOTSTRAP_ENV_FILE}
     fi
 
+    echo ""
+    echo " *******************************************"
     echo " * System Details:"
     echo "     OS Architecture: ${OS_ARCHITECTURE}"
     echo "     OS Type: ${OS_TYPE}"
     echo "     OS Distribution ID: ${OS_DISTRIBUTION_ID}"
     echo "     OS Distribution Codename: ${OS_DISTRIBUTION_CODENAME}"
     echo "     OS Distribution Release: ${OS_DISTRIBUTION_RELEASE}"
+    echo " *******************************************"
+    echo ""
+
+    if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
+        if [ -z "${bootstrap_subcommand}" ]; then
+            main
+            exit 0
+        fi
+    fi
 
     bootstrap_subcommand=${bootstrap_subcommand:-$OPENBATON_BOOTSTRAP_SUBCOMMAND_DEFAULT}
-    case ${bootstrap_subcommand} in
-        "help")
-            usage
-            exit 1
-            ;;
-        "release" )
-            echo " * Installing the latest RELEASE package"
-            main_deb release "${OS_DISTRIBUTION_CODENAME}"
-            ;;
-        "develop" )
-            # Check for OS: the develop installation works (i.e.: it has been tested) on Ubuntu 16.04 or later
-            if [ "${OS_DISTRIBUTION_ID}" = "Ubuntu" -a "${OS_DISTRIBUTION_RELEASE}" \< "16.04" ]; then
-                echo " * Sorry, If you want to install the source code through this bootstrap you need a machine with Ubuntu Xenial (16.04) or later."
-                echo " * In case you want to install the source code on a different OS you need to manually install Java 8 (if needed) and clone the repositories from ${OPENBATON_HOME_REPO_URL}"
-                exit 0
-            fi
+    exec_bootstrap_subcommand "${bootstrap_subcommand}"
 
-            echo " * Installing the latest source code"
-            main_src
-            ;;
-        "clean" )
-            echo " * Cleaning the Open Baton installation"
-            prereq
-            clean
-            exit 0
-            ;;
-        "enable-persistence" )
-            prereq
-            install_mysql
-            exit 0
-            ;;
-        "configure-remote-rabbitmq" )
-            prereq
-            configure_remote_rabbitmq
-            exit 0
-            ;;
-        "*")
-            usage
-            exit 1 
-            ;;
-    esac
 else # When invoked with 0 arguments: 'sh <(curl -s http://get.openbaton.org/bootstrap)'
+    echo ""
+    echo " *******************************************"
     echo " * System Details:"
     echo "     OS Architecture: ${OS_ARCHITECTURE}"
     echo "     OS Type: ${OS_TYPE}"
     echo "     OS Distribution ID: ${OS_DISTRIBUTION_ID}"
     echo "     OS Distribution Codename: ${OS_DISTRIBUTION_CODENAME}"
     echo "     OS Distribution Release: ${OS_DISTRIBUTION_RELEASE}"
+    echo " *******************************************"
+    echo ""
 
     main
 fi
diff --git a/bootstrap-common-functions b/bootstrap-common-functions
--- a/bootstrap-common-functions
+++ b/bootstrap-common-functions
@@ -131,7 +131,18 @@ enable_https () {
 
     # In case of "noninteractive" FRONTEND the default value will remain valid (see in lines below)
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-        read -p " * Do you want to enable HTTPS? [N/y]: " https
+        #read -p " * Do you want to enable HTTPS? [N/y]: " https
+        if (whiptail --title "${component_name_fancy} installation" --yesno "Do you want to enable HTTPS?" 8 140) then
+            https="yes"
+        else
+            https="no"
+        fi
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
     fi
 
     https=${https:-$HTTPS_DEFAULT}
@@ -210,17 +221,37 @@ configure_mysql () {
 
     # In case of "noninteractive" FRONTEND the default value will remain valid (openbaton_nfvo_mysql_user: admin ; openbaton_nfvo_mysql_user_password: changeme)
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-        read -p " * Please, type the name of the MySQL user you would like the Open Baton NFVO to use [admin]: " openbaton_nfvo_mysql_user
+        #read -p " * Please, type the name of the MySQL user you would like the Open Baton NFVO to use [admin]: " openbaton_nfvo_mysql_user
+	    openbaton_nfvo_mysql_user=$(whiptail --inputbox "\nPlease, type the name of the MySQL user you would like the Open Baton NFVO to use [admin]:" 8 140 admin --title "MySQL configuration for the NFVO" 3>&1 1>&2 2>&3)
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
 
         # Turning echo ON and OFF between password reading
-        stty -echo
-        read -p " * Please, provide the password for this user [changeme]: " openbaton_nfvo_mysql_user_password ; echo
-        stty echo
+        #stty -echo
+        #read -p " * Please, provide the password for this user [changeme]: " openbaton_nfvo_mysql_user_password ; echo
+        #stty echo
+        openbaton_nfvo_mysql_user_password=$(whiptail --passwordbox "\nPlease, provide the password for this user [changeme]:" 8 140 changeme --title "MySQL configuration for the NFVO" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
 
         # Turning echo ON and OFF batween password reading
-        stty -echo
-        read -p " * Please, provide the password of the 'root' user of MySQL [root]: " mysql_root_password ; echo
-        stty echo
+        #stty -echo
+        #read -p " * Please, provide the password of the 'root' user of MySQL [root]: " mysql_root_password ; echo
+        #stty echo
+        mysql_root_password=$(whiptail --passwordbox "\nPlease, provide the password of the 'root' user of MySQL [root]:" 8 140 root --title "MySQL configuration for the NFVO" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
     fi
 
     # Set the mysql user
@@ -249,7 +280,18 @@ install_mysql () {
 
     # In case of "noninteractive" FRONTEND the default value will remain valid (mysql: yes)
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-        read -p " * Do you want to enable the Open Baton persistence through MySQL? [Y/n]: " mysql
+        #read -p " * Do you want to enable the Open Baton persistence through MySQL? [Y/n]: " mysql
+        if (whiptail --title "MySQL configuration for the NFVO" --yesno "Do you want to enable the Open Baton persistence through MySQL?" 8 140) then
+            mysql="yes"
+        else
+            mysql="no"
+        fi
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
     else
         if [ "${mysql}" = "" -o "${mysql}" = "y" -o "${mysql}" = "Y" -o "${mysql}" = "yes" ]; then
             export mysql_root_password=${mysql_root_password:-$MYSQL_ROOT_PASSWORD_DEFAULT}
@@ -297,24 +339,77 @@ configure_remote_rabbitmq () {
 
     log_success_msg "Configuring remote RabbitMQ for Open Baton"
 
-    read -p " * Please provide the Open Baton NFVO version for which you want to configure the RabbitMQ Broker? (version format: 1) X.Y.Z for specific debian release/source tag, 2) 'latest' if the develop source code branch is installed) [latest]: " openbaton_nfvo_version
+    #read -p " * Please provide the Open Baton NFVO version for which you want to configure the RabbitMQ Broker? (version format: 1) X.Y.Z for specific debian release/source tag, 2) 'latest' if the develop source code branch is installed) [latest]: " openbaton_nfvo_version
+    openbaton_nfvo_version=$(whiptail --inputbox "\nPlease, provide the Open Baton NFVO version for which you want to configure the RabbitMQ Broker [latest]:\nVersion format:\n 1) X.Y.Z for specific debian release/source tag\n 2) 'latest' if the develop source code branch is installed)" 25 140 latest --title "Remote RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+    exit_status="$?"
+    if [ ${exit_status} != 0 ]; then
+        echo ""
+        log_warning_msg "Aborting remote RabbitMQ configuration"
+        exit 1
+    fi
     openbaton_nfvo_version=${openbaton_nfvo_version:-$OPENBATON_NFVO_VERSION_DEFAULT}
 
-    read -p " * Please provide the IP of the remote RabbitMQ Broker? [localhost]: " rabbitmq_broker_ip
-    read -p " * Please provide the 'management port' of the remote RabbitMQ Broker? [15672]: " rabbitmq_management_port
-
+    #read -p " * Please provide the IP of the remote RabbitMQ Broker? [localhost]: " rabbitmq_broker_ip
+    #read -p " * Please provide the 'management port' of the remote RabbitMQ Broker? [15672]: " rabbitmq_management_port
+    rabbitmq_broker_ip=$(whiptail --inputbox "\nPlease, provide the IP of the remote RabbitMQ Broker [localhost]:" 8 140 localhost --title "Remote RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+    exit_status="$?"
+    if [ ${exit_status} != 0 ]; then
+        echo ""
+        log_warning_msg "Aborting remote RabbitMQ configuration"
+        exit 1
+    fi
+    rabbitmq_management_port=$(whiptail --inputbox "\nPlease, provide the 'management port' of the remote RabbitMQ Broker [15672]:" 8 140 15672 --title "Remote RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+    exit_status="$?"
+    if [ ${exit_status} != 0 ]; then
+        echo ""
+        log_warning_msg "Aborting remote RabbitMQ configuration"
+        exit 1
+    fi
     rabbitmq_broker_ip=${rabbitmq_broker_ip:-$RABBITMQ_BROKER_IP_DEFAULT}
     rabbitmq_management_port=${rabbitmq_management_port:-$RABBITMQ_MANAGEMENT_PORT_DEFAULT}
+
     retrieve_rabbitmqadmin_cli ${rabbitmq_broker_ip} ${rabbitmq_management_port}
 
     #### NFVO configuration
-    read -p " * Does an 'admin' user exist in the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host? [Y/n]: " rabbitmq_admin_user
+    #read -p " * Does an 'admin' user exist in the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host? [Y/n]: " rabbitmq_admin_user
+    if (whiptail --title "Remote RabbitMQ configuration for the NFVO" --yesno "Does an 'admin' user exist in the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?" 8 140) then
+        rabbitmq_admin_user="yes"
+    else
+        rabbitmq_admin_user="no"
+    fi
+    exit_status="$?"
+    if [ ${exit_status} != 0 ]; then
+        echo ""
+        log_warning_msg "Aborting Open Baton installation"
+        exit 1
+    fi
 
     if [ "${rabbitmq_admin_user}" = "" -o "${rabbitmq_admin_user}" = "y" -o "${rabbitmq_admin_user}" = "Y" -o "${rabbitmq_admin_user}" = "yes" ]; then
-        read -p " * Please provide the 'admin' password of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?: " rabbitmq_admin_password
+        #read -p " * Please provide the 'admin' password of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?: " rabbitmq_admin_password
+        rabbitmq_admin_password=$(whiptail --passwordbox "\nPlease, provide the 'admin' password of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host:" 8 140 --title "Remote RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting remote RabbitMQ configuration"
+            exit 1
+        fi
     else
-        read -p " * Please provide the username of an user of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?: " rabbitmq_user_username
-        read -p " * Please provide the password of the '${rabbitmq_user_username}' user of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?: " rabbitmq_user_password
+        #read -p " * Please provide the username of an user of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?: " rabbitmq_user_username
+        #read -p " * Please provide the password of the '${rabbitmq_user_username}' user of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host?: " rabbitmq_user_password
+        rabbitmq_user_username=$(whiptail --inputbox "\nPlease, provide the username of an existing user of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host:" 8 140 --title "Remote RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting remote RabbitMQ configuration"
+            exit 1
+        fi
+        rabbitmq_user_password=$(whiptail --passwordbox "\nPlease, provide the password of the '${rabbitmq_user_username}' user of the remote RabbitMQ Broker on the '${rabbitmq_broker_ip}' host:" 8 140 --title "Remote RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting remote RabbitMQ configuration"
+            exit 1
+        fi
 
         # Generate the password and creates the 'admin' user if not already existing
         # Check the NFVO version being installed: the new RabbitMQ configuration is required only from version >= 4.0.1
@@ -400,7 +495,12 @@ create_service () {
     export nfvo_user="admin"
     export nfvo_admin_password=$( awk '$0 ~ "nfvo.security.admin.password[[:space:]]*="' "${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}" | awk -F'=' '{print $2}' )
     export nfvo_ip=$( awk '$0 ~ "nfvo.rabbit.brokerIp[[:space:]]*="' "${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}" | awk -F'=' '{print $2}' )
-    export nfvo_port="8080"
+    https_enabled=$(cat ${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE} | grep "nfvo.https=true" | wc -l)
+    if [ "${https_enabled}" = "1" ]; then
+        export nfvo_port=$( awk '$0 ~ "server.port[[:space:]]*="' "${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}" | awk -F'=' '{print $2}' )
+    else
+        export nfvo_port="8080"
+    fi
     log_success_msg "NFVO_USER: ${nfvo_user}"
     log_success_msg "NFVO_ADMIN_PASSWORD: ****"
     log_success_msg "NFVO_USER: ${nfvo_ip}"
@@ -461,11 +561,26 @@ clean_db () {
     # Clean MySQL for Components
     component_mysql_user=${component_mysql_user:-"undefined"}
     if [ "${component_mysql_user}" != "undefined" ]; then
-        read -p " * Do you want to delete the Open Baton ${component_name_fancy} database: '${component_db_name}' (this will also delete the associated user: '${component_mysql_user}')? (if you skip this step then you won't be able, later on, to delete this database and its user using this script) [Y/n]: " mysql
-        if [ "${mysql}" = "" -o "${mysql}" = "y" -o "${mysql}" = "Y" -o "${mysql}" = "yes" ]; then
-            stty -echo
-            read -p " * Please, provide the password of the 'root' user of mysql [root]: " mysql_root_password ; echo
-            stty echo
+        #read -p " * Do you want to delete the Open Baton ${component_name_fancy} database: '${component_db_name}' (this will also delete the associated user: '${component_mysql_user}')? (if you skip this step then you won't be able, later on, to delete this database and its user using this script) [Y/n]: " mysql
+        #if [ "${mysql}" = "" -o "${mysql}" = "y" -o "${mysql}" = "Y" -o "${mysql}" = "yes" ]; then
+        if (whiptail --title "\nOpen Baton ${component_name_fancy} installation cleaning" --yesno "Do you want to delete the Open Baton ${component_name_fancy} database: '${component_db_name}' (this will also delete the associated user: '${component_mysql_user}')?\n(if you skip this step then you won't be able, later on, to delete this database and its user using this script):" 8 140) then
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting Open Baton ${component_name_fancy} installation cleaning"
+                exit 1
+            fi
+
+            #stty -echo
+            #read -p " * Please, provide the password of the 'root' user of mysql [root]: " mysql_root_password ; echo
+            #stty echo
+            mysql_root_password=$(whiptail --passwordbox "\nPlease, provide the password of the 'root' user of mysql [root]:" 8 140 root --title "Open Baton ${component_name_fancy} installation cleaning" 3>&1 1>&2 2>&3)
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting Open Baton ${component_name_fancy} installation cleaning"
+                exit 1
+            fi
 
             echo " * Deleting Open Baton ${component_name_fancy} database and its associated user."
             mysql_root_password=${mysql_root_password:-$MYSQL_ROOT_PASSWORD_DEFAULT}
diff --git a/bootstrap-deb-functions b/bootstrap-deb-functions
--- a/bootstrap-deb-functions
+++ b/bootstrap-deb-functions
@@ -44,16 +44,26 @@ deb_install_nfvo () {
     export nfvo_version="${3}"
 
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
+        available_tags=$(curl -s GET https://api.github.com/repos/openbaton/${OPENBATON_NFVO_REPO_NAME}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_nfvo_version_supported}" '$1 >= oldest')
+
         valid_version=false
         while [ "${valid_version}" = "false" ]; do
             # Ask for the NFVO version to be installed
-            read -p " * Which VERSION of the Open Baton NFVO do you want to install (Version Format is X.Y.Z - ** ${oldest_nfvo_version_supported} is the oldest version supported ** - Check the list of available VERSIONs at: ${OPENBATON_NFVO_REPO_URL}/tags )? (latest): " nfvo_version
+            #read -p " * Which VERSION of the Open Baton NFVO do you want to install (Version Format is X.Y.Z - ** ${oldest_nfvo_version_supported} is the oldest version supported ** - Check the list of available VERSIONs at: ${OPENBATON_NFVO_REPO_URL}/tags )? (latest): " nfvo_version
+            nfvo_version=$(whiptail --inputbox "Which VERSION of the Open Baton NFVO do you want to install?\nThe available choices installable with this bootstrap are the following:\n\n$(echo "latest\n${available_tags}")" 25 140 latest --title "Open Baton NFVO installation" 3>&1 1>&2 2>&3)
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting Open Baton installation"
+                exit 1
+            fi
 
             if [ "${nfvo_version}" = "" -o "${nfvo_version}" = "latest" ]; then
                 valid_version=true
                 continue
             else
-                result=$( echo ${nfvo_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                #result=$( echo ${nfvo_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                result="1"
                 if [ "${result}" != "0" ]; then
                     valid_version=true
                     continue
@@ -117,32 +127,74 @@ deb_install_additional_component () {
 
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
         # Ask for the specified Additional Component installation
-        read -p " * Do you want to install also the Open Baton ${component_name_fancy}? ( if you do not, then you can still install it later with: sudo apt-get install openbaton-${component_name} ) (Y/n): " ac
+        #read -p " * Do you want to install also the Open Baton ${component_name_fancy}? ( if you do not, then you can still install it later with: sudo apt-get install openbaton-${component_name} ) (Y/n): " ac
 
-        # Print correct warning message
-        if [ "${ac}" = "n" -o "${ac}" = "N" -o "${ac}" = "no" -o "${ac}" = "NO" ]; then
-            echo " * Open Baton ${component_name_fancy} not installed"
-            if [ "${release_nightly}" = "release" ]; then
-                echo " * To install the latest release package:"
-                echo " *     sudo apt-get install openbaton-${component_name}"
-            else
-                echo " * To install the latest nightly-build package:"
-                echo " *     sudo apt-get install openbaton-${component_name}-nightly"
+        ## Print correct warning message
+        #if [ "${ac}" = "n" -o "${ac}" = "N" -o "${ac}" = "no" -o "${ac}" = "NO" ]; then
+        #    echo " * Open Baton ${component_name_fancy} not installed"
+        #    if [ "${release_nightly}" = "release" ]; then
+        #        echo " * To install the latest release package:"
+        #        echo " *     sudo apt-get install openbaton-${component_name}"
+        #    else
+        #        echo " * To install the latest nightly-build package:"
+        #        echo " *     sudo apt-get install openbaton-${component_name}-nightly"
+        #    fi
+        #    return
+        #else
+        #    # Install the correct Additional Component package according to the given input parameter
+        #    if [ ${force_component_version} != "true" ]; then 
+        #        valid_version=false
+        #        while [ "${valid_version}" = "false" ]; do
+        #            # Ask for the Additional Component version to be installed
+        #            read -p " * Which VERSION of the Open Baton ${component_name_fancy} do you want to install (Version Format is X.Y.Z - *** ${oldest_component_version_supported} is the oldest version supported ** - Check the list of available VERSIONs at: ${component_repo_url}/tags )? (latest): " component_version
+
+        #            if [ "${component_version}" = "" -o "${component_version}" = "latest" ]; then
+        #                valid_version=true
+        #                continue
+        #            else
+        #                result=$( echo ${component_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+        #                if [ "${result}" != "0" ]; then
+        #                    valid_version=true
+        #                    continue
+        #                fi
+        #            fi
+        #        done
+        #    fi
+
+        #    deb_install_additional_component_versioned
+        #fi
+
+        if (whiptail --title "${component_name_fancy} installation" --yesno "Do you want to install also the ${component_name_fancy}?\nIf you do not, then you can still install it later with:\n sudo apt-get install openbaton-${component_name}" 15 140) then
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting Open Baton installation"
+                exit 1
             fi
-            return
-        else
+
             # Install the correct Additional Component package according to the given input parameter
             if [ ${force_component_version} != "true" ]; then 
+                available_tags=$(curl -s GET ${component_repo_url}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_component_version_supported}" '$1 >= oldest')
+
                 valid_version=false
                 while [ "${valid_version}" = "false" ]; do
                     # Ask for the Additional Component version to be installed
-                    read -p " * Which VERSION of the Open Baton ${component_name_fancy} do you want to install (Version Format is X.Y.Z - *** ${oldest_component_version_supported} is the oldest version supported ** - Check the list of available VERSIONs at: ${component_repo_url}/tags )? (latest): " component_version
+                    #read -p " * Which VERSION of the Open Baton ${component_name_fancy} do you want to install (Version Format is X.Y.Z - *** ${oldest_component_version_supported} is the oldest version supported ** - Check the list of available VERSIONs at: ${component_repo_url}/tags )? (latest): " component_version
+
+                    component_version=$(whiptail --inputbox "Which VERSION of the Open Baton ${component_name_fancy} do you want to install?\nThe available choices installable with this bootstrap are the following:\n\n$(echo "develop\n${available_tags}")" 25 140 latest --title "Open Baton ${component_name_fancy} installation" 3>&1 1>&2 2>&3)
+                    exit_status="$?"
+                    if [ ${exit_status} != 0 ]; then
+                        echo ""
+                        log_warning_msg "Aborting Open Baton installation"
+                        exit 1
+                    fi
 
                     if [ "${component_version}" = "" -o "${component_version}" = "latest" ]; then
                         valid_version=true
                         continue
                     else
-                        result=$( echo ${component_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                        #result=$( echo ${component_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                        result="1"
                         if [ "${result}" != "0" ]; then
                             valid_version=true
                             continue
@@ -152,6 +204,16 @@ deb_install_additional_component () {
             fi
 
             deb_install_additional_component_versioned
+        else
+            echo " * Open Baton ${component_name_fancy} not installed"
+            if [ "${release_nightly}" = "release" ]; then
+                echo " * To install the latest release package:"
+                echo " *     sudo apt-get install openbaton-${component_name}"
+            else
+                echo " * To install the latest nightly-build package:"
+                echo " *     sudo apt-get install openbaton-${component_name}-nightly"
+            fi
+            return
         fi
     else
         if [ "${install_during_noninteractive_installation}" = "y" -o "${install_during_noninteractive_installation}" = "Y" -o "${install_during_noninteractive_installation}" = "yes" ]; then
diff --git a/bootstrap-src-functions b/bootstrap-src-functions
--- a/bootstrap-src-functions
+++ b/bootstrap-src-functions
@@ -85,8 +85,22 @@ src_configure_rabbitmq_for_nfvo () {
 
         # In case of "noninteractive" FRONTEND either the value from the configuration file or the default value will be used (DEFAULT: rabbitmq_broker_ip=localhost ; rabbitmq_management_port=15672)
         if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-            read -p " * Enter the rabbitmq broker ip [localhost]: " rabbitmq_broker_ip
-            read -p " * Enter the rabbitmq management port [15672]: " rabbitmq_management_port
+            #read -p " * Enter the rabbitmq broker ip [localhost]: " rabbitmq_broker_ip
+            #read -p " * Enter the rabbitmq management port [15672]: " rabbitmq_management_port
+            rabbitmq_broker_ip=$(whiptail --inputbox "\nEnter the RabbitMQ broker IP:" 8 140 localhost --title "RabbitMQ configuration for the NFVO" 3>&1 1>&2 2>&3)
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+            echo ""
+                log_warning_msg "Aborting Open Baton installation"
+                exit 1
+            fi
+            rabbitmq_management_port=$(whiptail --inputbox "\nEnter the RabbitMQ management port:" 8 140 15672 --title "RabbitMQ configuration for NFVO" 3>&1 1>&2 2>&3)
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+            echo ""
+                log_warning_msg "Aborting Open Baton installation"
+                exit 1
+            fi
         fi
 
         export OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE=${OPENBATON_NFVO_CONFIG_FILE_ABSOLUTE}
@@ -235,20 +249,31 @@ src_checkout_nfvo () {
     export nfvo_version="${2}"
 
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
+	export OPENBATON_NFVO_REPO_NAME
+	available_tags=$(curl -s GET https://api.github.com/repos/openbaton/${OPENBATON_NFVO_REPO_NAME}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_nfvo_version_supported}" '$1 >= oldest')
+
         valid_version=false
         while [ "${valid_version}" = "false" ]; do
             # Ask for the NFVO version to be installed
-            echo " * You can install a specific TAG of the Open Baton NFVO or the latest source code of the 'develop' branch of the repository."
-            echo " * For the latest code of the 'develop' branch type 'develop'"
-            echo " * For a specific TAG, the format is X.Y.Z and the available TAGs installable with this bootstrap are the following:"
-            curl -s GET https://api.github.com/repos/openbaton/${OPENBATON_NFVO_REPO_NAME}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_nfvo_version_supported}" '$1 >= oldest'
-            read -p " * Which VERSION of the Open Baton NFVO do you want to install? (develop): " nfvo_version
+            #echo " * You can install a specific TAG of the Open Baton NFVO or the latest source code of the 'develop' branch of the repository."
+            #echo " * For the latest code of the 'develop' branch type 'develop'"
+            #echo " * For a specific TAG, the format is X.Y.Z and the available TAGs installable with this bootstrap are the following:"
+            #curl -s GET https://api.github.com/repos/openbaton/${OPENBATON_NFVO_REPO_NAME}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_nfvo_version_supported}" '$1 >= oldest'
+            #read -p " * Which VERSION of the Open Baton NFVO do you want to install? (develop): " nfvo_version
+            nfvo_version=$(whiptail --inputbox "\nYou can install a specific TAG of the Open Baton NFVO or the latest source code of the 'develop' branch of the repository.\nThe available choices installable with this bootstrap are the following:\n\n$(echo "develop\n${available_tags}")\n\nWhich VERSION of the Open Baton NFVO do you want to install?" 25 140 develop --title "NFVO installation" 3>&1 1>&2 2>&3)
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting Open Baton installation"
+                exit 1
+            fi
 
             if [ "${nfvo_version}" = "" -o "${nfvo_version}" = "develop" ]; then
                 valid_version=true
                 continue
             else
-                result=$( echo ${nfvo_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                #result=$( echo ${nfvo_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                result="1"
                 if [ "${result}" != "0" ]; then
                     valid_version=true
                     continue
@@ -256,6 +281,8 @@ src_checkout_nfvo () {
             fi
         done
     fi
+
+    # Needed in case of Noninteractive installation
     if [ "${nfvo_version}" = "" -o "${nfvo_version}" = "latest" ]; then
         nfvo_version="develop"
     fi
@@ -299,15 +326,31 @@ src_set_nfvo_admin_credentials () {
     # In case of "noninteractive" FRONTEND the default value will remain valid (user: admin ; password: openbaton)
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
         # Turning echo ON and OFF between password reading
-        stty -echo
-        read -p " * Provide the new password for 'admin' user of Open Baton [openbaton]: " openbaton_admin_password ; echo
-        stty echo
+        #stty -echo
+        #read -p " * Provide the new password for 'admin' user of Open Baton [openbaton]: " openbaton_admin_password ; echo
+        #stty echo
+
+        openbaton_admin_password=$(whiptail --passwordbox "\nProvide the new password for 'admin' user of open baton [openbaton]:" 8 140 openbaton --title "NFVO configuration" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
 
         if [ "${openbaton_admin_password}" != "" ]; then
             # Turning echo ON and OFF between password reading
-            stty -echo
-            read -p " * Repeat the 'admin' password: " openbaton_admin_password_again ; echo
-            stty echo
+            #stty -echo
+            #read -p " * Repeat the 'admin' password: " openbaton_admin_password_again ; echo
+            #stty echo
+            openbaton_admin_password_again=$(whiptail --passwordbox "\nRepeat the 'admin' password:" 8 140 --title "NFVO configuration" 3>&1 1>&2 2>&3)
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting open baton installation"
+                exit 1
+            fi
+
             if [ "${openbaton_admin_password}" != "${openbaton_admin_password_again}" ]; then
                 src_set_nfvo_admin_credentials
             fi
@@ -360,22 +403,42 @@ src_checkout_additional_component () {
 
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
         # Ask for the specified Additional Component installation
-        read -p " * Do you want to install also the ${component_name_fancy}? ( if you do not, then you can still install it later with: cd ${OPENBATON_BASE_DIR} && git clone ${component_repo_url}.git ) (Y/n): " ac
+        #read -p " * Do you want to install also the ${component_name_fancy}? ( if you do not, then you can still install it later with: cd ${OPENBATON_BASE_DIR} && git clone ${component_repo_url}.git ) (Y/n): " ac
+        #if [ "${ac}" = "" -o "${ac}" = "y" -o "${ac}" = "Y" -o "${ac}" = "yes" -o "${ac}" = "YES" ]; then
+        if (whiptail --title "${component_name_fancy} installation" --yesno "Do you want to install also the ${component_name_fancy}?\nIf you do not, then you can still install it later with:\n cd ${OPENBATON_BASE_DIR} && git clone ${component_repo_url}.git" 15 140) then
+            exit_status="$?"
+            if [ ${exit_status} != 0 ]; then
+                echo ""
+                log_warning_msg "Aborting Open Baton installation"
+                exit 1
+            fi
 
-        if [ "${ac}" = "" -o "${ac}" = "y" -o "${ac}" = "Y" -o "${ac}" = "yes" -o "${ac}" = "YES" ]; then
             valid_version=false
             while [ "${valid_version}" = "false" ]; do
-                echo " * You can install a specific TAG of the Open Baton ${component_name_fancy} or the latest source code of the 'develop' branch of the repository."
-                echo " * For the latest code of the 'develop' branch type 'develop'"
-                echo " * For a specific TAG, the format is X.Y.Z and the available TAGs installable with this bootstrap are the following: "
-                curl -s GET https://api.github.com/repos/openbaton/${component_name}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_component_version_supported}" '$1 >= oldest'
-                read -p " * Which VERSION of the Open Baton ${component_name_fancy} do you want to install? (develop): " component_version
+                export component_name
+                export component_name_fancy
+                export oldest_component_version_supported
+
+                available_tags=$(curl -s GET https://api.github.com/repos/openbaton/${component_name}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_component_version_supported}" '$1 >= oldest')
+                #echo " * You can install a specific TAG of the Open Baton ${component_name_fancy} or the latest source code of the 'develop' branch of the repository."
+                #echo " * For the latest code of the 'develop' branch type 'develop'"
+                #echo " * For a specific TAG, the format is X.Y.Z and the available TAGs installable with this bootstrap are the following: "
+                #curl -s GET https://api.github.com/repos/openbaton/${component_name}/tags | grep "name\":" | awk -F':' '{print $2}' | awk -F'"' '{print $2}' | awk -v oldest="${oldest_component_version_supported}" '$1 >= oldest'
+                #read -p " * Which VERSION of the Open Baton ${component_name_fancy} do you want to install? (develop): " component_version
+                component_version=$(whiptail --inputbox "\nYou can install a specific TAG of the Open Baton ${component_name_fancy} or the latest source code of the 'develop' branch of the repository.\nThe available choices installable with this bootstrap are the following:\n\n$(echo "develop\n${available_tags}")\n\nWhich VERSION of the Open Baton ${component_name_fancy} do you want to install?" 25 140 develop --title "Open Baton ${component_name_fancy} installation" 3>&1 1>&2 2>&3)
+                exit_status="$?"
+                if [ ${exit_status} != 0 ]; then
+                    echo ""
+                    log_warning_msg "Aborting Open Baton installation"
+                    exit 1
+                fi
 
                 if [ "${component_version}" = "" -o "${component_version}" = "develop" ]; then
                     valid_version=true
                     continue
                 else
-                    result=$( echo ${component_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                    #result=$( echo ${component_version} | grep "^[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$" | wc -l )
+                    result="1"
                     if [ "${result}" != "0" ]; then
                         valid_version=true
                         continue
@@ -499,7 +562,14 @@ src_fms_configure_nfvo () {
 
     # In case of "noninteractive" FRONTEND the default value will remain valid (openbaton_nfvo_ip: localhost)
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-       read -p " * Please, provide the IP of the NFVO [localhost]: " openbaton_nfvo_ip
+        #read -p " * Please, provide the IP of the NFVO [localhost]: " openbaton_nfvo_ip
+        openbaton_nfvo_ip=$(whiptail --inputbox "\nEnter the IP of the NFVO:" 8 140 localhost --title "Fault Management System configuration" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
     fi
     # Set the NFVO IP
     export openbaton_nfvo_ip=${openbaton_nfvo_ip:-$OPENBATON_NFVO_IP_DEFAULT}
@@ -522,17 +592,38 @@ src_fms_configure_mysql () {
 
     # In case of "noninteractive" FRONTEND the default value will remain valid (openbaton_fms_mysql_user: fmsuser ; openbaton_fms_mysql_user_password: changeme)
     if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
-        read -p " * Please, type the name of the MySQL user you would like the Open Baton FMS to use [fmsuser]: " openbaton_fms_mysql_user
+        #read -p " * Please, type the name of the MySQL user you would like the Open Baton FMS to use [fmsuser]: " openbaton_fms_mysql_user
+        openbaton_fms_mysql_user=$(whiptail --inputbox "\nPlease, type the name of the MySQL user you would like the Open Baton FMS to use:" 8 140 fmsuser --title "Fault Management System configuration" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
 
         # Turning echo ON and OFF between password reading
-        stty -echo
-        read -p " * Please, provide the password for this user [changeme]: " openbaton_fms_mysql_user_password ; echo
-        stty echo
+        #stty -echo
+        #read -p " * Please, provide the password for this user [changeme]: " openbaton_fms_mysql_user_password ; echo
+        #stty echo
+        openbaton_fms_mysql_user_password=$(whiptail --passwordbox "\nPlease, provide the password for this user [changeme]:" 8 140 changeme --title "Fault Management System configuration" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
 
         # Turning echo ON and OFF batween password reading
-        stty -echo
-        read -p " * Please, provide the password of the 'root' user of MySQL [root]: " mysql_root_password ; echo
-        stty echo
+        #stty -echo
+        #read -p " * Please, provide the password of the 'root' user of MySQL [root]: " mysql_root_password ; echo
+        #stty echo
+        mysql_root_password=$(whiptail --passwordbox "\nPlease, provide the password of the 'root' user of MySQL [root]:" 8 140 root --title "Fault Management System configuration" 3>&1 1>&2 2>&3)
+        exit_status="$?"
+        if [ ${exit_status} != 0 ]; then
+            echo ""
+            log_warning_msg "Aborting Open Baton installation"
+            exit 1
+        fi
     fi
 
     # Set the MySQL user
@@ -650,7 +741,7 @@ src_bootstrap () {
     wait_for_nfvo_up
     echo " * Now open http://localhost:8080/"
 
-    if [ -f "${BOOTSTRAP_DIR}/bootstrap-src-functions" ]; then
-        rm ${BOOTSTRAP_DIR}/bootstrap-src-functions
-    fi
+    #if [ -f "${BOOTSTRAP_DIR}/bootstrap-src-functions" ]; then
+    #    rm ${BOOTSTRAP_DIR}/bootstrap-src-functions
+    #fi
 }
